### ISSUE TITLE
Add Open Graph meta tags

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#69]
It would be nice to have reaching level 3 but having level 1 would be a good compromise, for now.

Standard/preview: https://www.opengraph.xyz/url/https%3A%2F%2Fipfs-search.com/
Vue.js metadata plugin: https://vue-meta.nuxtjs.org/

## Level 1

- [x] Static OpenGraph tags for ipfs-search.com and a static preview.

## Level 2

- [ ] Search-query level tagging (e.g. search query and type in page title and OG), with same static image preview.

## Level 3
Title and description of detail pages, 

- [ ] image where available.

**Comment by Szeket** [comment]
I am trying to do that now. At least the level 1.

**Comment by femans** [comment]
level 1 is done by #253
